name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
          waybackpack: waybackpack-0.3.0
        - os: ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: pip install waybackpack
      run: |
        waybackpack=${{matrix.waybackpack || 'waybackpack'}}
        python3 -m pip install ${waybackpack/-/==}
    - name: run tests
      run:
        WAYBACKPACK4GIT_NETWORK_TESTING=1 prove -v
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
